global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'task-manager-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s
