apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: dockeramiro/ucb-task-service:v1.0.2
        env:
        - name: DATABASE_URL
          # value: "mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@mysql.app-namespace:3306/taskdb"
          value: "mysql://taskuser:taskpass@mysql.app-namespace:3306/taskdb"
        - name: PORT
          value: "3001"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 40
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: app-namespace
spec:
  selector:
    app: task-service
  ports:
    - port: 3001
      targetPort: 3001
  type: LoadBalancer