apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: dockeramiro/ucb-user-service:v1.0.1
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/userdb"
        - name: PORT
          value: "3002"
        ports:
        - containerPort: 3002
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 40
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: app-namespace
spec:
  selector:
    app: user-service
  ports:
    - port: 3002
      targetPort: 3002
  type: LoadBalancer